---
- hosts: all

- hosts: webservers
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/ubuntu/.gem/ruby/2.3.0/bin/"
    RAILS_ENV: production
  roles:
    - common
    - postgres
    - nginx
    - node
    - ruby
    - app
