---

- name: Install bundler
  gem: 
    name: bundler
    state: latest

- name: Update path to include ruby gems
  lineinfile:
    name: /home/ubuntu/.bashrc
    regexp: '^PATH='
    line: "PATH=$PATH:~/.gem/ruby/2.3.0/bin"

- name: Setup bundler
  shell: bundle config build.nio4r --with-cflags="-std=c99"

- name: Clone project repository
  git: 
    repo: git://github.com/chrislaskey/community-share.git 
    dest: /home/ubuntu/current
    accept_hostkey: true

- name: Create ENV file
  template:
    src: .env.j2
    dest: /home/ubuntu/current/.env

- name: Install project gems
  shell: cd current && bash -lc "bundle install"

- name: Install project database
  shell: cd current && bash -lc "bundle exec rake db:create db:migrate db:seed"
