---

- name: Install puma systemd file
  template:
    src: etc/systemd/system/puma.service
    dest: /etc/systemd/system/puma.service
    mode: 0755
  become: true

- name: Enable puma on restart
  shell: systemctl enable puma.service
  become: true

- name: Reload systemctl daemon
  shell: systemctl daemon-reload
  become: true

- name: Stop puma service
  shell: systemctl stop puma.service
  become: true

- name: Remove puma temp files
  shell: rm -rf /home/ubuntu/current/tmp/puma
  become: true

- name: Start puma service
  shell: systemctl start puma.service
  become: true
